// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplicationMenu() {
  return window['go']['main']['App']['ApplicationMenu']();
}

export function EncodeIcoFromPngBase64(arg1, arg2) {
  return window['go']['main']['App']['EncodeIcoFromPngBase64'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}
