// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function AppVersion():Promise<string>;

export function ApplicationMenu():Promise<menu.Menu>;

export function EncodeIcoFromPngBase64(arg1:string,arg2:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;
